In [1]:
import pandas as pd
import numpy as np
input_data = pd.read_csv(r"C:\Users\chvsa\Desktop\ML Assignment\Fish.csv")
print(input_data)
print(type(input_data))

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\chvsa\\Desktop\\ML Assignment\\Fish.csv'

In [633]:
from sklearn.preprocessing import OneHotEncoder
cat_encoder = OneHotEncoder()
input_data_1hot = cat_encoder.fit_transform(input_data)
input_data_1hot.toarray()

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [634]:
import pandas as pd
import numpy as np
input_data = input_data[['Length1','Length2','Length3','Height','Width']].values.astype(float)
input_data_std = (input_data - input_data.min()) / (input_data.max() - input_data.min())
input_data_std







array([[0.3308679 , 0.36372707, 0.43243259, 0.1564156 , 0.04439572],
       [0.34281669, 0.37716945, 0.45035578, 0.17075415, 0.04866144],
       [0.34132309, 0.38015665, 0.44886218, 0.16922769, 0.05449394],
       [0.37716945, 0.41749661, 0.48470854, 0.17448814, 0.05090034],
       [0.38015665, 0.41749661, 0.49217653, 0.17021645, 0.06103441],
       [0.38463744, 0.4279518 , 0.50263172, 0.1875183 , 0.05794863],
       [0.38463744, 0.4279518 , 0.49964452, 0.19613785, 0.06319266],
       [0.39658623, 0.43243259, 0.50711252, 0.17359198, 0.05440283],
       [0.39658623, 0.43243259, 0.50860611, 0.19353003, 0.05669998],
       [0.41002862, 0.44288778, 0.5250357 , 0.19684134, 0.05842658],
       [0.40853502, 0.44736858, 0.5250357 , 0.19738202, 0.06058931],
       [0.41301581, 0.44736858, 0.5250357 , 0.19900407, 0.05626385],
       [0.41899021, 0.45483657, 0.52802289, 0.18986026, 0.04959344],
       [0.4249646 , 0.46230456, 0.54146528, 0.19215592, 0.06012032],
       [0.423471  , 0.46230456, 0.

In [635]:
import pandas as pd
import numpy as np
#from sklearn.cross_validation import train_test_split
#output_data=Weight
# Selecting the features
features = ['Weight','Length1','Length2','Length3','Height','Width']
fish= df[features]

# Target Variable
y = df['Weight']
fish_train, fish_test, y_train, y_test = train_test_split(fish, y, test_size = 0.40, random_state = 200 )
#input_data_train, input_data_test = train_test_split(input_data, test_size = 0.4, random_state = 200)
print(fish_train)
print(y_train)

train_test_split




     Weight  Length1  Length2  Length3   Height   Width
114   700.0     34.5     37.0     39.4  10.8350  6.2646
25    725.0     31.8     35.0     40.9  16.3600  6.0532
130   300.0     32.7     35.0     38.8   5.9364  4.3844
63     90.0     16.3     17.7     19.8   7.4052  2.6730
32    925.0     36.2     39.5     45.3  18.7542  6.7497
..      ...      ...      ...      ...      ...     ...
42    120.0     19.4     21.0     23.7   6.1146  3.2943
68    145.0     19.8     21.5     24.1   9.7364  3.1571
16    700.0     30.4     33.0     38.3  14.8604  5.2854
105   250.0     25.4     27.5     28.9   7.2828  4.5662
26    720.0     32.0     35.0     40.6  16.3618  6.0900

[95 rows x 6 columns]
114    700.0
25     725.0
130    300.0
63      90.0
32     925.0
       ...  
42     120.0
68     145.0
16     700.0
105    250.0
26     720.0
Name: Weight, Length: 95, dtype: float64


<function sklearn.model_selection._split.train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)>

In [649]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import mean_squared_error
# from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(fish_train,y_train) #actually produces the linear eqn for the data
y_pred = regressor.predict(fish_test) 
y_pred

array([279.41568507, 321.5384325 , 471.46980074, 524.94488805,
       293.18532177, 496.98509667, 361.73762044, 443.78202425,
       287.78184265, 463.07601266, 488.80422716, 265.75266554,
       383.38924582, 296.67704992, 379.38323316, 265.86264158,
       401.56988483, 394.02237605, 485.33766073, 368.0944587 ,
       341.31696278, 468.9841164 , 392.14955242, 470.81857909,
       461.61743689, 326.3129835 , 423.79246362, 392.1855266 ,
       318.36790693, 444.94184495, 262.45454483, 457.92287637,
       312.76576988, 267.57729938, 340.89383334, 556.68668957,
       246.0585668 , 293.61921216, 403.76857951, 326.96083437,
       530.57457624, 340.73242023, 297.80634639, 307.32981702,
       337.42652847, 494.04337901, 452.55603397, 499.0220432 ,
       361.92258331, 406.74293781, 281.2091548 , 325.31706612,
       335.72984065, 459.79119814, 272.93178441, 442.83976571,
       296.71255572, 503.1243035 , 315.08748535, 441.05731203,
       246.33015242, 491.47588528, 457.41081405, 326.88

In [642]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
# print('Root Mean Squared training Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred)))
# print('Root Mean Squared test Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 2.3743507160389754e-13
Mean Squared Error: 1.0296992767683716e-25


In [643]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly=PolynomialFeatures(degree=30)
fish_train_poly=poly.fit_transform(fish_train)
fish_test_poly = poly.fit_transform(fish_test)
print(fish_train)
fish_train_poly[0]
poly_model =LinearRegression()
print(fish_train_poly)
print(fish_train)

     Weight  Length1  Length2  Length3   Height   Width
114   700.0     34.5     37.0     39.4  10.8350  6.2646
25    725.0     31.8     35.0     40.9  16.3600  6.0532
130   300.0     32.7     35.0     38.8   5.9364  4.3844
63     90.0     16.3     17.7     19.8   7.4052  2.6730
32    925.0     36.2     39.5     45.3  18.7542  6.7497
..      ...      ...      ...      ...      ...     ...
42    120.0     19.4     21.0     23.7   6.1146  3.2943
68    145.0     19.8     21.5     24.1   9.7364  3.1571
16    700.0     30.4     33.0     38.3  14.8604  5.2854
105   250.0     25.4     27.5     28.9   7.2828  4.5662
26    720.0     32.0     35.0     40.6  16.3618  6.0900

[95 rows x 6 columns]
[[1.00000000e+00 7.00000000e+02 3.45000000e+01 ... 2.41363460e+24
  1.39551964e+24 8.06864084e+23]
 [1.00000000e+00 7.25000000e+02 3.18000000e+01 ... 2.10449188e+24
  7.78661995e+23 2.88104938e+23]
 [1.00000000e+00 3.00000000e+02 3.27000000e+01 ... 3.31536270e+19
  2.44860121e+19 1.80844403e+19]
 ...
 [1

In [644]:
poly_model.fit(fish_train_poly, y_train)
poly_model.coef_
poly_model.intercept_
poly_train_pred = poly_model.predict(fish_train_poly)
poly_test_pred = poly_model.predict(fish_test_poly)
poly_train_pred = poly_model.predict(fish_train_poly)
poly_test_pred = poly_model.predict(fish_test_poly)

print('Root Mean Squared training Error:', np.sqrt(metrics.mean_squared_error(y_train, poly_train_pred)))
print('Root Mean Squared test Error:', np.sqrt(metrics.mean_squared_error(y_test, poly_test_pred)))

Root Mean Squared training Error: 417.503869190985
Root Mean Squared test Error: 791742055940.1473


In [645]:
import pandas as pd
import numpy as np
#from sklearn.cross_validation import train_test_split
#output_data=Weight
# Selecting the features
variables = ['Weight','Length1','Length2','Length3','Height','Width']
fish= df[variables]

# Target Variable
s = df['Species']
fish_train, fish_test, y_train, y_test = train_test_split(fish, y, test_size = 0.40, random_state = 400 )
#input_data_train, input_data_test = train_test_split(input_data, test_size = 0.4, random_state = 200)
print(fish_train)
print(s_train)
train_test_split


     Weight  Length1  Length2  Length3   Height   Width
40      0.0     19.0     20.5     22.8   6.4752  3.3516
113   700.0     34.0     36.0     38.3  10.6091  6.7408
125  1100.0     40.1     43.0     45.5  12.5125  7.4165
156    12.2     12.1     13.0     13.8   2.2770  1.2558
8     450.0     27.6     30.0     35.1  14.0049  4.8438
..      ...      ...      ...      ...      ...     ...
6     500.0     26.8     29.7     34.5  14.1795  5.2785
151    10.0     11.3     11.8     13.1   2.2139  1.2838
140   950.0     48.3     51.7     55.1   8.9262  6.1712
62     60.0     14.3     15.5     17.4   6.5772  2.3142
92    150.0     20.5     22.5     24.0   6.7920  3.6240

[95 rows x 6 columns]
142         Pike
58     Whitefish
106        Perch
96         Perch
54         Roach
         ...    
150        Smelt
47         Roach
21         Bream
29         Bream
41         Roach
Name: Species, Length: 95, dtype: object


<function sklearn.model_selection._split.train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)>

In [646]:
# Splitting the dataset into the training and test set
fish_train, fish_test, s_train, s_test = train_test_split(fish, s, test_size = 0.40, random_state = 200 )
# Fitting SGD Classifier to the Training set
model = SGDClassifier(loss="hinge", alpha=0.01, max_iter=200)
model.fit(fish_train, s_train)
# Predicting the results
s_pred = model.predict(fish_test)
# Confusion matrix
print("Confusion Matrix")
matrix = confusion_matrix(s_test, s_pred)
print(matrix)
# Classification Report
print("\nClassification Report")
report = classification_report(s_test, s_pred)
print(report)
# Accuracy of the model
accuracy = accuracy_score(s_test, s_pred)
# print('SGD Classifier Accuracy of the model: {:.2f}%'.format(accuracy*100))

Confusion Matrix
[[16  0  0  0  0  0  0]
 [ 3  0  0  0  0  0  0]
 [19  0  0  0  0  1  5]
 [ 7  0  0  0  0  0  0]
 [ 6  0  0  0  0  0  2]
 [ 0  3  0  0  0  0  0]
 [ 2  0  0  0  0  0  0]]

Classification Report
              precision    recall  f1-score   support

       Bream       0.30      1.00      0.46        16
      Parkki       0.00      0.00      0.00         3
       Perch       0.00      0.00      0.00        25
        Pike       0.00      0.00      0.00         7
       Roach       0.00      0.00      0.00         8
       Smelt       0.00      0.00      0.00         3
   Whitefish       0.00      0.00      0.00         2

    accuracy                           0.25        64
   macro avg       0.04      0.14      0.07        64
weighted avg       0.08      0.25      0.12        64



C:\Users\chvsa\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\chvsa\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\chvsa\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [647]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
fish_train, fish_test, s_train, s_test=train_test_split(fish, s, test_size=0.40)

knc = KNeighborsClassifier(n_neighbors=40)
print(knc)

knc.fit(fish_train, s_train)
score = knc.score(fish_train, s_train)
print("Score: ", score)

s_pred = knc.predict(fish_test)

cm = confusion_matrix(s_test, s_pred)
print(cm)

cr = classification_report(s_test, s_pred)
print(cr)

KNeighborsClassifier(n_neighbors=40)
Score:  0.4
[[15  0  1  0  1  0]
 [ 0  0  6  0  0  0]
 [ 5  0 14  0  1  0]
 [ 6  0  3  0  0  0]
 [ 0  0  6  0  0  0]
 [ 0  0  6  0  0  0]]
              precision    recall  f1-score   support

       Bream       0.58      0.88      0.70        17
      Parkki       0.00      0.00      0.00         6
       Perch       0.39      0.70      0.50        20
        Pike       0.00      0.00      0.00         9
       Roach       0.00      0.00      0.00         6
       Smelt       0.00      0.00      0.00         6

    accuracy                           0.45        64
   macro avg       0.16      0.26      0.20        64
weighted avg       0.27      0.45      0.34        64



C:\Users\chvsa\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\chvsa\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\chvsa\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
