In [ ]:
from google.colab import drive
#drive.mount('/content/drive')

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
from google.colab import files
import pandas as pd
import io
import matplotlib.pyplot as plt
from sklearn import linear_model
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, MinMaxScaler, PolynomialFeatures, StandardScaler
from sklearn import preprocessing, metrics
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, f1_score
from sklearn.metrics import precision_score
from sklearn.model_selection import  GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from pandas import DataFrame
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier

#uploading the data

input_data = pd.read_csv("/content/drive/My Drive/HW2ML.csv")
input_data.head()

# data.head()

input_data.isnull().any()
input_data['emotion'].unique()
df = DataFrame(input_data)
data_dictionay = {0:'anger', 1:'disgust', 2:'fear', 3:'happiness', 4: 'sadness', 5: 'surprise', 6: 'neutral'}

input_data['emotion'].value_counts()

input_data.dtypes

emotion     int64
 Usage     object
 pixels    object
dtype: object

In [ ]:
# assigning variables to the data
y = input_data['emotion']

x=input_data[' pixels'].apply(lambda x : np.array(x.split(' ')).astype(float))

B.shape  
 

(250, 2304)

In [ ]:
#printing pixel values 

x = np.stack(x, axis=0)
print(x)

[[ 70.  80.  82. ... 106. 109.  82.]
 [151. 150. 147. ... 193. 183. 184.]
 [231. 212. 156. ...  88. 110. 152.]
 ...
 [ 10.  11.  11. ...  13.  16.  21.]
 [148. 151. 149. ... 184. 182. 180.]
 [ 43.  42.  36. ... 103.  97.  95.]]


In [ ]:
#diving the data test and train set and printing the data 

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=35)
# print(B_train)
# print(B_test)
# print(a_train)
# print(a_test)


In [ ]:
#alling the lenghts of the data for easy computation

len(x_train)  == len(y_train)

print(len(x_train))
print(len(y_train))



187
187


# SVM POLYNOMIAL

In [ ]:
svm_poly_estimator = Pipeline(steps=[('scaler', StandardScaler()), ('estimator', SVC())])

svm_poly_params = [{'estimator__kernel': ["poly"],        
                   'estimator__degree': [5,10,40],        
                   'estimator__C': [0.1,10,1000],    
                   'estimator__gamma': [.00001,.0001,.01,1,1.5]}] 
        

svm_poly_grid = GridSearchCV(estimator=svm_poly_estimator,
                       param_grid=svm_poly_params,
                       cv=5,
                       n_jobs=-1,)

svm_poly_grid.fit(B_train, a_train) 


print('svm_poly F1: ', f1_score(a,svm_poly_grid.predict(B), average='micro'))
print('best svm_poly_parameters', svm_poly_grid.best_estimator_)

KeyboardInterrupt: ignored

# SVM RBF

In [ ]:
# svm_rbf_estimator = Pipeline(steps=[('scaler', StandardScaler()), ('estimator', SVC())])

# svm_rbf_params = [{'estimator__kernel': ["rbf"],        
#                    'estimator__degree': [5,10,40],        
#                    'estimator__C': [0.1,10,1000],    
#                    'estimator__gamma': [.00001,.0001,.01,1,1.5]}] 
        
# svm_rbf_grid = GridSearchCV(estimator=svm_rbf_estimator,
#                        param_grid=svm_rbf_params,
#                        cv=5,
#                        n_jobs=-1,)

# svm_rbf_grid.fit(B_train, a_train) 


# print('svm_poly F1: ', f1_score(a,svm_rbf_grid.predict(B), average='micro'))
# print('best svm_rbf_parameters', svm_rbf_grid.best_params_)

svm_rbf_estimator = Pipeline(steps=[('scaler', StandardScaler()), ('estimator', SVC())])
svm_rbf_params = [{'estimator__kernel': ["rbf"],
'estimator__degree': [2,6,20],
'estimator__C': [0.1,10,1000],
'estimator__gamma': [.00001,.0001,.01,1,1.5]}]
svm_rbf_grid = GridSearchCV(estimator=svm_rbf_estimator,
param_grid=svm_rbf_params,
cv=5,
n_jobs=-1,)
svm_rbf_grid.fit(x_train, y_train)
print('svm_poly F1: ', f1_score(y,svm_rbf_grid.predict(x), average='micro'))
print('best svm_rbf_parameters', svm_rbf_grid.best_estimator_)

svm_poly F1:  0.244
best svm_rbf_parameters Pipeline(memory=None,
         steps=[('scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('estimator',
                 SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None,
                     coef0=0.0, decision_function_shape='ovr', degree=2,
                     gamma=1e-05, kernel='rbf', max_iter=-1, probability=False,
                     random_state=None, shrinking=True, tol=0.001,
                     verbose=False))],
         verbose=False)


# Decision tree

In [ ]:
#Decission tree 

# dt_params = {
#     'max_depth': [3,5,7,8,10]
# }


# decision_grid = GridSearchCV(DecisionTreeClassifier(),dt_params)

# decision_grid.fit(B_train, a_train)


# # best = decision_grid.best_estimator_
# # print(best)

# predict_values = decision_grid.predict(B_test)

# best.fit(B_train, a_train)

# f1_score  = f1_score(a_test, predict_values,average='micro')
# print(f1_score)
# print('best decision_grid ', decision_grid.best_params_)

params_dec = {
'max_depth': [2,4,6,8,10]
}
decision_grid = GridSearchCV(DecisionTreeClassifier(),params_dec)
decision_grid.fit(y_train, x_train).array.reshape(-1, 1)
best = decision_grid.best_estimator_
print(best)
predict_values = decision_grid.predict(y_test)
best.fit(y_train, x_train)
f1_score = f1_score(a_test, predict_values,average='micro')
print(f1_score)


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Expected 2D array, got 1D array instead:
array=[0. 3. 0. 6. 0. 4. 3. 4. 5. 3. 3. 3. 4. 2. 2. 2. 0. 2. 6. 3. 0. 5. 5. 0.
 3. 6. 3. 6. 0. 4. 4. 6. 3. 6. 6. 5. 3. 3. 2. 0. 3. 3. 5. 0. 4. 6. 6. 0.
 6. 2. 4. 6. 5. 5. 2. 2. 2. 6. 3. 2. 4. 3. 2. 4. 3. 5. 3. 2. 4. 0. 3. 3.
 6. 2. 5. 4. 3. 0. 3. 2. 2. 3. 2. 2. 5. 3. 0. 0. 0. 6. 0. 5. 3. 0. 3. 2.
 0. 3. 5. 3. 0. 2. 6. 3. 4. 5. 2. 0. 2. 0. 3. 5. 0. 4. 0. 5. 3. 2. 2. 2.
 3. 4. 2. 0. 3. 2. 0. 0. 0. 5. 6. 0. 4. 6. 6. 3. 2. 0. 3. 3. 3. 3. 5. 3.
 2. 4. 4. 5. 6.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

  FitFailedWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimato

ValueError: ignored

# KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import f1_score, accuracy_score

knn_estimator = Pipeline(steps=[('scaler', StandardScaler()), ('estimator', KNeighborsClassifier())])

knn_params = [{'estimator__n_neighbors': np.arange(1, 85).astype('int')}]

knn_grid = GridSearchCV(estimator=knn_estimator,                        
                        param_grid=knn_params,                        
                        cv=5,                       
                        n_jobs=-1,                     
                        scoring = 'f1_micro') 
knn_grid.fit(x_train, y_train)
print('knn F1: ', f1_score(y_train, knn_grid.predict(x_train), average='micro'))
print('best_knn_parameters: ', knn_grid.best_params_)

knn F1:  0.2727272727272727
best_knn_parameters:  {'estimator__n_neighbors': 33}


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score, accuracy_score

random_forest = Pipeline(steps=[('scaler', StandardScaler()), ('estimator', RandomForestClassifier())])

random_forest_params = [{'estimator__n_neighbors': np.arange(1, 85).astype('int')}]

random_forest_grid = GridSearchCV(estimator=random_forest,                        
                        param_grid=random_forest_params,                        
                        cv=5,                       
                        n_jobs=-1,                     
                        scoring = 'f1_micro') 
random_forest_grid.fit(x_train, y_train)
print('knn F1: ', f1_score(y_train, random_forest_grid.predict(x_train), average='micro'))
print('best_random_forest_parameters: ', random_forest_grid.best_params_)